### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mgalczynski** [scicup/scicup.com-students#1]
![image](https://cloud.githubusercontent.com/assets/11553284/19794550/7088c37c-9cd3-11e6-9d5f-de07931e408c.png)
![image](https://cloud.githubusercontent.com/assets/11553284/19794554/7a89399c-9cd3-11e6-988a-b8e3ba7fb8fc.png)

**Comment by scicup** [comment]
Thanks for submitting. It is fixed now.
