### ISSUE TITLE
Kodowanie plików

### ISSUE THREAD

**Issue by CyberKot93** [scicup/scicup.com-students#10]
nie ma podanego kodowania plików, co bardzo waży w podanych danych od SPA, gdyż bez tego dane wczytywane są niepoprawnie, a ma to znaczenie dla poprawności predykcji i końcowego wyniku

**Comment by scicup** [comment]
Kodowanie plików opisane jest w Data files/Important notes:
"All files are ANSI encoded and contain “\r\n” line breaks."

Czy o to chodziło?

**Comment by CyberKot93** [comment]
rzeczywiście, nie zauważyłem;)
