### ISSUE TITLE
Landing page [EN]: typo / grammar

### ISSUE THREAD

**Issue by dziabdak** [scicup/scicup.com-students#2]
[...]They solve problems, **_won_**  prizes, find jobs and make contacts.[...]
won -> win 

`<p data-caption-animate="fadeInUp" data-caption-delay="200">People take machine learning challenges here. They solve problems,  prizes, find jobs and make contacts. This is open science platform.</p>`

**Comment by scicup** [comment]
Thanks, it was fixed in the language files and the change will be put online with the newest update of the platform this week.
