### ISSUE TITLE
Błędna ścieżka podczas załączania pliku w systemach unixowych

### ISSUE THREAD

**Issue by novirael** [scicup/scicup.com-students#5]
![screenshot 2016-10-30 00 06 10](https://cloud.githubusercontent.com/assets/6555610/19833061/9287e210-9e35-11e6-8b01-f47d05e5c1c8.png)

**Comment by scicup** [comment]
Próbujemy usunąć ścieżkę tak aby pojawiała się tam tylko nazwa pliku.

**Comment by scicup** [comment]
Problem rozwiązany - pojawia się tylko nazwa pliku.
