### ISSUE TITLE
Zgłoszenie może zostać wysłane bez akceptacji regulaminu

### ISSUE THREAD

**Issue by novirael** [scicup/scicup.com-students#6]
![fazgu63fga](https://cloud.githubusercontent.com/assets/6555610/19833082/362a3df0-9e36-11e6-997d-d47df418eb47.gif)

**Comment by scicup** [comment]
Dziękuję za zgłoszenie. Problem rozwiązany, obecnie wyskakuje komunikat o konieczności akceptacji zasad konkursu.
